PS C:\GRPC> & "C:/Program Files/Python310/python.exe" c:/GRPC/Server/grpc_server.py
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1736853813.927152   13448 chttp2_server.cc:1177] UNKNOWN:No address added out of total 1 resolved for '[::]:9090' {created_time:"2025-01-14T11:23:33.9271368+00:00", children:[UNKNOWN:Failed to prepare server socket {created_time:"2025-01-14T11:23:33.9270132+00:00"
, fd:576, children:[UNAVAILABLE:bind: WSA Error (Only one usage of each socket address (protocol/network address/port) is normally permitted.
 -- 10048) {created_time:"2025-01-14T11:23:33.9269295+00:00", grpc_status:14}]}]}
Traceback (most recent call last):
  File "c:\GRPC\Server\grpc_server.py", line 41, in <module>
    serve()
  File "c:\GRPC\Server\grpc_server.py", line 28, in serve
    server.add_insecure_port('[::]:9090')
  File "C:\Program Files\Python310\lib\site-packages\grpc\_server.py", line 1473, in add_insecure_port
    return _common.validate_port_binding_result(
  File "C:\Program Files\Python310\lib\site-packages\grpc\_common.py", line 181, in validate_port_binding_result
    raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
RuntimeError: Failed to bind to address [::]:9090; set GRPC_VERBOSITY=debug environment variable to see detailed error message.